"@context":

ontologies:

## URCH

  - id: urch
    preferredPrefix: URCH
    title: Sea Urchin Ontology
    uri: http://purl.obolibrary.org/obo/urch.owl
    base_uri:
      - http://purl.obolibrary.org/obo/URCH_
    reasoner: EL
    oboSlims: false
    ontology_purl : file:///opt/ols/ontologies/urch.owl